using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Shared.Input;
using System.Numerics;
using Robust.Shared.Prototypes;
using Content.Shared._FarHorizons.Research;
using Robust.Client.ResourceManagement;
using Content.Client._FarHorizons.Research.UI.Helpers;
using Content.Client._FarHorizons.Research.UI.Helpers.Search;
using System.Linq;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FHResearchTree : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    public Action<ProtoId<ResearchTreeNodePrototype>?>? OnSelectionChanged;

    private bool _moving = false;
    private Vector2 _viewportPosition = Vector2.Zero;
    private Vector2 _pseudoViewport => (_viewportPosition * _zoom) + (_viewportSize / 2);
    private Vector2 _lastViewportPosition = Vector2.Zero;
    private Vector2 _lastMousePos = Vector2.Zero;
    private List<DrawResearchTier> _tiers = [];
    private List<DrawResearchNode> _nodes = [];
    private List<DrawResearchEdge> _edges = [];
    private bool _draw = false;
    private readonly Font _font;

    private ProtoId<ResearchTreeNodePrototype>? _hovered = null;
    private ProtoId<ResearchTreeNodePrototype>? _selected = null;

    private ProtoId<ResearchTreeNodePrototype>? _willSelect = null;

    private HashSet<ProtoId<ResearchTreeTierPrototype>> _unlockedTiers = [];
    private HashSet<ProtoId<ResearchTreeNodePrototype>> _unlockedNodes = [];
    private HashSet<ProtoId<ResearchTreeNodePrototype>> _researched = [];
    private Dictionary<ProtoId<ResearchTreeNodePrototype>, float> _researching = [];

    private Vector2 _currentMousePosition => 
        (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
    
    private Vector2 _viewportSize =>
        new(Width * UIScale, Height * UIScale);
    
    private readonly ResearchSearch _search;
    
    private const float MaxZoom = 1.5f;
    private const float MinZoom = 0.3f;
    private const float ZoomSpeed = 0.2f;
    private readonly TimeSpan _zoomAnimSpeed = TimeSpan.FromSeconds(0.15f);
    private TimeSpan _zoomAnimFrom = TimeSpan.Zero;
    private TimeSpan _zoomAnimTo = TimeSpan.Zero;
    private float _zoomFrom = 1;
    private float _zoomTo = 1;
    private float _zoomProgress => Math.Clamp((float)(_timing.CurTime - _zoomAnimFrom).TotalSeconds / (float)(_zoomAnimTo - _zoomAnimFrom).TotalSeconds, 0f, 1f);
    private float _zoom
    {
        get => (_zoomFrom * (1 - _zoomProgress)) + (_zoomTo * _zoomProgress);
        set
        {
            _zoomFrom = value;
            _zoomTo = value;
        }
    }

    public int NodeWidth = 100;
    public int NodeHeight = 30;

    public int NodeSpacingHorizontal = 75;
    public int NodeSpacingVertical = 35;

    public int NodeMarginHorizontal = 10;
    public int NodeMarginVertical = 10;

    public string FontPath = "/EngineFonts/NotoSans/NotoSansMono-Regular.ttf";
    public string SearchTexturePath = "/Textures/Interface/VerbIcons/examine.svg.192dpi.png";
    private readonly Texture _searchTexture;

    private readonly SearchDatabase _searchDb = new();

    public FHResearchTree()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        var resourceCache = IoCManager.Resolve<IResourceCache>();

        var fontResource = resourceCache.GetResource<FontResource>(FontPath);
        _font = new VectorFont(fontResource, 16);
        _searchTexture = resourceCache.GetResource<TextureResource>(SearchTexturePath).Texture;

        CanKeyboardFocus = true;
        DefaultCursorShape = CursorShape.Arrow;
        _search = new(_timing, _prototypeManager, _font, _searchTexture);
    }
    
    public void BuildTree(
        HashSet<ResearchTreeNodePrototype> nodes,
        HashSet<ProtoId<ResearchTreeTierPrototype>> unlockedTiers,
        HashSet<ProtoId<ResearchTreeNodePrototype>> unlockedNodes,
        HashSet<ProtoId<ResearchTreeNodePrototype>> researched,
        Dictionary<ProtoId<ResearchTreeNodePrototype>, float> progress
    )
    {   
        var grid = new ResearchTreeGrid(_prototypeManager, nodes);

        (_tiers, _nodes, _edges) = grid.GetDrawable((NodeWidth, NodeHeight), (NodeSpacingHorizontal, NodeSpacingVertical), (NodeMarginHorizontal, NodeMarginVertical), _font);
        _draw = true;
        _unlockedTiers = unlockedTiers;
        _unlockedNodes = unlockedNodes;
        _researched = researched;
        _researching = progress;

        _viewportPosition = (-_viewportSize / 2) + new Vector2(NodeMarginHorizontal * 2, NodeMarginVertical * 2);

        _searchDb.Build(_prototypeManager, [.. nodes.Select(p => (ProtoId<ResearchTreeNodePrototype>)p.ID)]);
        _search.SetDb(_searchDb);
        _search.OnSearchSelected += (node) => Select(node);
    }

    public void RefreshTree(
        HashSet<ProtoId<ResearchTreeTierPrototype>> unlockedTiers,
        HashSet<ProtoId<ResearchTreeNodePrototype>> unlockedNodes,
        HashSet<ProtoId<ResearchTreeNodePrototype>> researched,
        Dictionary<ProtoId<ResearchTreeNodePrototype>, float> progress
    )
    {
        _unlockedTiers = unlockedTiers;
        _unlockedNodes = unlockedNodes;
        _researched = researched;
        _researching = progress;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (_search.Active && args.Function == EngineKeyFunctions.TextBackspace)
            _search.Backspace();

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;
        
        if (_search.AnyMouseOver)
            return;
        
        _lastViewportPosition = _viewportPosition;
        if (_nodes.Any(p => p.Proto == _hovered && p.Zoom(_zoom).Translate(_pseudoViewport).IsHovering(_currentMousePosition)))
        {
            _willSelect = _hovered;
            return;
        }

        DefaultCursorShape = CursorShape.Move;
        _moving = true;
        _lastMousePos = _currentMousePosition;
        UserInterfaceManager.ClickSound();
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        if (_search.AnyMouseOver)
            _search.OnClicked();
        
        if (_search.Active)
            GrabKeyboardFocus();
        else
            ReleaseKeyboardFocus();

        DefaultCursorShape = CursorShape.Arrow;
        _moving = false;
        UserInterfaceManager.ClickSound();

        if (_lastViewportPosition != _viewportPosition)
            return;

        var lastSelection = _selected;
        _selected = _hovered != null && _hovered == _willSelect ? _hovered : null;
        if (lastSelection != _selected)
            OnSelectionChanged?.Invoke(_selected);
    }
    
    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        if (args.Handled)
            return;
        
        _zoomFrom = _zoom;
        _zoomTo = Math.Clamp(_zoom + (args.Delta.Y * ZoomSpeed), MinZoom, MaxZoom);
        _zoomAnimFrom = _timing.CurTime;
        _zoomAnimTo = _zoomAnimFrom + _zoomAnimSpeed;
    }

    protected override void KeyboardFocusEntered()
    {
        base.KeyboardFocusEntered();

        if (_search.Active)
            Root?.Window?.TextInputStart();
    }

    protected override void KeyboardFocusExited()
    {
        base.KeyboardFocusEntered();

        if (!_search.Active)
            Root?.Window?.TextInputStop();
    }

    protected override void TextEntered(GUITextEnteredEventArgs args)
    {
        if (!_search.Active)
            return;
        
        _search.UpdateText(args.Text);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_draw)
            return;

        _search.Update(handle, _viewportSize, _currentMousePosition);

        MoveViewport();
        foreach (var tier in _tiers)
            tier
            .Zoom(_zoom)
            .Translate(_pseudoViewport)
            .DrawBg(handle);
        _hovered = GetHovered();
        foreach (var edge in _edges)
            edge
            .Zoom(_zoom)
            .Translate(_pseudoViewport)
            .Hovered(_hovered)
            .Research(_researched)
            .Draw(handle);
        for (var i = 0; i < _nodes.Count; i++)
        {
            _nodes[i] = _nodes[i].WrapName(handle); // basically part of initialization, but it requires handle so it's here. Will only run first time
            _nodes[i]
            .Zoom(_zoom)
            .Translate(_pseudoViewport)
            .Hovered(_currentMousePosition)
            .Select(_selected)
            .Unlock(_unlockedTiers, _unlockedNodes)
            .Research(_researched)
            .Researching(_researching)
            .Draw(handle);
        }
        foreach (var tier in _tiers)
            tier
            .Zoom(_zoom)
            .Translate(_pseudoViewport)
            .DrawHeader(handle);
        
        _search.Draw(handle);
    }

    private void MoveViewport()
    {
        if (!_moving)
            return;

        var curMousePos = _currentMousePosition;
        _viewportPosition += (_currentMousePosition - _lastMousePos) * (MaxZoom - (_zoom - MinZoom));
        _lastMousePos = curMousePos;
    }

    private ProtoId<ResearchTreeNodePrototype>? GetHovered()
    {
        var hovered = _nodes
        .Where(p => p.Zoom(_zoom).Translate(_pseudoViewport).IsHovering(_currentMousePosition))
        .Select(p => p.Proto)
        .ToList();

        return hovered.Count > 0 ? hovered.First() : (ProtoId<ResearchTreeNodePrototype>?)null;
    }

    public void Select(ProtoId<ResearchTreeNodePrototype>? select)
    {
        if (_selected != select)
        {
            _selected = select;
            OnSelectionChanged?.Invoke(_selected);
            var node = _nodes.Where(p => p.Proto == _selected).First();
            _viewportPosition = -node.Position - (node.Size / 2);
            _zoom = 1;
        }
    }
}
